### ISSUE TITLE
Provide a More Descriptive Authentication Error Message

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#63] opened 2011-06-07 15:00 UTC
When a user only provides his user name instead of the whole user string (e.g. <username>@wisebed1.itm.uni-luebeck.de) he gets an authentication error saying something like "An error occured." This message should be more descriptive as provided by the actual exception.

**Comment by master-lincoln** [comment] 2011-06-07 17:40
I investigated on this but I don't get any further:

in `client/testbedlist/util/AuthenticationHelper.java` method `onFailure(final Throwable caught)` I get an `eu.wisebed.wiseui.shared.exception.AuthenticationException`

The "actual" Exception is the cause ( `eu.wisebed.api.snaa.SNAAExceptionException`) which is generated on the server. But if I do `caught.getCause()` I get no response. This might be due to the RPC characteristics...

I already implemented a way to show custom error messages but I can't access the "actual" Exception...

An idea would be to change the `SNAAServiceImpl.java` in Line 74 to:

<pre>
} catch (final SNAAExceptionException e) {
    LOGGER.error(AUTHENTICATION_FAILED, e);
    throw new AuthenticationException(e.getMessage(), e);
}
</pre>


If thats OK for you I can commit...

**Comment by soenkenils** [comment] 2011-06-08 11:37
Yes, please change the two exception blocks accordingly.

**Comment by master-lincoln** [comment] 2011-06-08 11:52
Should be fixed now but I couldn't test yet...

**Closed as completed** 2011-06-08 20:52 UTC
Labels: in progress, task
